
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btn_updateUI;

	private global::Gtk.CheckButton ck_autoUpdateUI;

	private global::Gtk.Label l_frameNumber;

	private global::Gtk.HBox l_hBoxMedia;

	private global::Gtk.HButtonBox l_hbuttonBoxTransport;

	private global::Gtk.Button btn_transportPrev;

	private global::Gtk.Button btn_transportNext;

	private global::Gtk.Button btn_transportPlay;

	private global::Gtk.Button btn_transportPause;

	private global::Gtk.Label l_mediaArtist;

	private global::Gtk.Label l_mediaTrack;

	private global::Gtk.Table l_tableMixer;

	private global::Gtk.Button btn_g1_mute;

	private global::Gtk.Button btn_g1_solo;

	private global::Gtk.VScale s_mainout;

	private global::Gtk.Button btn_forceCloseMidi;

	private global::Gtk.Button b_MidiLoad;

	private global::Gtk.Button b_MidiCFG;

	private global::Gtk.Button b_setMainOut;

	private global::Gtk.HBox l_hBoxStatus;

	private global::Gtk.Label l_stMidiDevice;

	private global::Gtk.Label l_stMidiMap;

	private global::Gtk.Label l_stMidiStatus;

	private global::Gtk.Label l_stIdkSomemore;

	private global::Gtk.Label l_stIdkSomemoremore;

	private global::Gtk.Label l_stCopyright;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("SharpMix (GTK)");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_updateUI = new global::Gtk.Button();
		this.btn_updateUI.CanFocus = true;
		this.btn_updateUI.Name = "btn_updateUI";
		this.btn_updateUI.UseUnderline = true;
		this.btn_updateUI.Label = global::Mono.Unix.Catalog.GetString("Update UI");
		this.fixed1.Add(this.btn_updateUI);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_updateUI]));
		w1.X = 1179;
		w1.Y = 660;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ck_autoUpdateUI = new global::Gtk.CheckButton();
		this.ck_autoUpdateUI.CanFocus = true;
		this.ck_autoUpdateUI.Name = "ck_autoUpdateUI";
		this.ck_autoUpdateUI.Label = global::Mono.Unix.Catalog.GetString("Auto Update UI");
		this.ck_autoUpdateUI.DrawIndicator = true;
		this.ck_autoUpdateUI.UseUnderline = true;
		this.fixed1.Add(this.ck_autoUpdateUI);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ck_autoUpdateUI]));
		w2.X = 1137;
		w2.Y = 613;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l_frameNumber = new global::Gtk.Label();
		this.l_frameNumber.Name = "l_frameNumber";
		this.l_frameNumber.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
		this.fixed1.Add(this.l_frameNumber);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l_frameNumber]));
		w3.X = 1225;
		w3.Y = 570;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l_hBoxMedia = new global::Gtk.HBox();
		this.l_hBoxMedia.WidthRequest = 1000;
		this.l_hBoxMedia.HeightRequest = 30;
		this.l_hBoxMedia.Name = "l_hBoxMedia";
		this.l_hBoxMedia.Spacing = 6;
		// Container child l_hBoxMedia.Gtk.Box+BoxChild
		this.l_hbuttonBoxTransport = new global::Gtk.HButtonBox();
		this.l_hbuttonBoxTransport.WidthRequest = 30;
		this.l_hbuttonBoxTransport.HeightRequest = 30;
		this.l_hbuttonBoxTransport.Name = "l_hbuttonBoxTransport";
		// Container child l_hbuttonBoxTransport.Gtk.ButtonBox+ButtonBoxChild
		this.btn_transportPrev = new global::Gtk.Button();
		this.btn_transportPrev.HeightRequest = 10;
		this.btn_transportPrev.CanFocus = true;
		this.btn_transportPrev.Name = "btn_transportPrev";
		this.btn_transportPrev.UseUnderline = true;
		this.btn_transportPrev.Label = global::Mono.Unix.Catalog.GetString("⏮");
		this.l_hbuttonBoxTransport.Add(this.btn_transportPrev);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.l_hbuttonBoxTransport[this.btn_transportPrev]));
		w4.Expand = false;
		w4.Fill = false;
		// Container child l_hbuttonBoxTransport.Gtk.ButtonBox+ButtonBoxChild
		this.btn_transportNext = new global::Gtk.Button();
		this.btn_transportNext.HeightRequest = 10;
		this.btn_transportNext.CanFocus = true;
		this.btn_transportNext.Name = "btn_transportNext";
		this.btn_transportNext.UseUnderline = true;
		this.btn_transportNext.Label = global::Mono.Unix.Catalog.GetString("⏭");
		this.l_hbuttonBoxTransport.Add(this.btn_transportNext);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.l_hbuttonBoxTransport[this.btn_transportNext]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child l_hbuttonBoxTransport.Gtk.ButtonBox+ButtonBoxChild
		this.btn_transportPlay = new global::Gtk.Button();
		this.btn_transportPlay.HeightRequest = 10;
		this.btn_transportPlay.CanFocus = true;
		this.btn_transportPlay.Name = "btn_transportPlay";
		this.btn_transportPlay.UseUnderline = true;
		this.btn_transportPlay.Label = "⏵";
		this.l_hbuttonBoxTransport.Add(this.btn_transportPlay);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.l_hbuttonBoxTransport[this.btn_transportPlay]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child l_hbuttonBoxTransport.Gtk.ButtonBox+ButtonBoxChild
		this.btn_transportPause = new global::Gtk.Button();
		this.btn_transportPause.HeightRequest = 10;
		this.btn_transportPause.CanFocus = true;
		this.btn_transportPause.Name = "btn_transportPause";
		this.btn_transportPause.UseUnderline = true;
		this.btn_transportPause.Label = global::Mono.Unix.Catalog.GetString("⏸");
		this.l_hbuttonBoxTransport.Add(this.btn_transportPause);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.l_hbuttonBoxTransport[this.btn_transportPause]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.l_hBoxMedia.Add(this.l_hbuttonBoxTransport);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.l_hBoxMedia[this.l_hbuttonBoxTransport]));
		w8.Position = 0;
		// Container child l_hBoxMedia.Gtk.Box+BoxChild
		this.l_mediaArtist = new global::Gtk.Label();
		this.l_mediaArtist.WidthRequest = 300;
		this.l_mediaArtist.Name = "l_mediaArtist";
		this.l_mediaArtist.LabelProp = global::Mono.Unix.Catalog.GetString("Artist: N/A");
		this.l_hBoxMedia.Add(this.l_mediaArtist);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.l_hBoxMedia[this.l_mediaArtist]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child l_hBoxMedia.Gtk.Box+BoxChild
		this.l_mediaTrack = new global::Gtk.Label();
		this.l_mediaTrack.WidthRequest = 300;
		this.l_mediaTrack.Name = "l_mediaTrack";
		this.l_mediaTrack.LabelProp = global::Mono.Unix.Catalog.GetString("Track: N/A");
		this.l_hBoxMedia.Add(this.l_mediaTrack);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.l_hBoxMedia[this.l_mediaTrack]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.fixed1.Add(this.l_hBoxMedia);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l_hBoxMedia]));
		w11.X = 5;
		w11.Y = 5;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l_tableMixer = new global::Gtk.Table(((uint)(3)), ((uint)(8)), false);
		this.l_tableMixer.WidthRequest = 1200;
		this.l_tableMixer.HeightRequest = 500;
		this.l_tableMixer.Name = "l_tableMixer";
		this.l_tableMixer.RowSpacing = ((uint)(6));
		this.l_tableMixer.ColumnSpacing = ((uint)(6));
		// Container child l_tableMixer.Gtk.Table+TableChild
		this.btn_g1_mute = new global::Gtk.Button();
		this.btn_g1_mute.CanFocus = true;
		this.btn_g1_mute.Name = "btn_g1_mute";
		this.btn_g1_mute.Label = global::Mono.Unix.Catalog.GetString("M");
		this.l_tableMixer.Add(this.btn_g1_mute);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.l_tableMixer[this.btn_g1_mute]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child l_tableMixer.Gtk.Table+TableChild
		this.btn_g1_solo = new global::Gtk.Button();
		this.btn_g1_solo.CanFocus = true;
		this.btn_g1_solo.Name = "btn_g1_solo";
		this.btn_g1_solo.UseUnderline = true;
		this.btn_g1_solo.Label = global::Mono.Unix.Catalog.GetString("S");
		this.l_tableMixer.Add(this.btn_g1_solo);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.l_tableMixer[this.btn_g1_solo]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child l_tableMixer.Gtk.Table+TableChild
		this.s_mainout = new global::Gtk.VScale(null);
		this.s_mainout.HeightRequest = 200;
		this.s_mainout.CanFocus = true;
		this.s_mainout.Name = "s_mainout";
		this.s_mainout.Inverted = true;
		this.s_mainout.Adjustment.Upper = 127D;
		this.s_mainout.Adjustment.PageIncrement = 1D;
		this.s_mainout.Adjustment.StepIncrement = 1D;
		this.s_mainout.Adjustment.Value = 99D;
		this.s_mainout.DrawValue = true;
		this.s_mainout.Digits = 0;
		this.s_mainout.ValuePos = ((global::Gtk.PositionType)(2));
		this.l_tableMixer.Add(this.s_mainout);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.l_tableMixer[this.s_mainout]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add(this.l_tableMixer);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l_tableMixer]));
		w15.X = 28;
		w15.Y = 65;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_forceCloseMidi = new global::Gtk.Button();
		this.btn_forceCloseMidi.CanFocus = true;
		this.btn_forceCloseMidi.Name = "btn_forceCloseMidi";
		this.btn_forceCloseMidi.UseUnderline = true;
		this.btn_forceCloseMidi.Label = global::Mono.Unix.Catalog.GetString("Force Stop Midi");
		this.fixed1.Add(this.btn_forceCloseMidi);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_forceCloseMidi]));
		w16.X = 1266;
		w16.Y = 700;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.b_MidiLoad = new global::Gtk.Button();
		this.b_MidiLoad.CanFocus = true;
		this.b_MidiLoad.Name = "b_MidiLoad";
		this.b_MidiLoad.UseUnderline = true;
		this.b_MidiLoad.Label = global::Mono.Unix.Catalog.GetString("Load Midi");
		this.fixed1.Add(this.b_MidiLoad);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.b_MidiLoad]));
		w17.X = 1071;
		w17.Y = 667;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.b_MidiCFG = new global::Gtk.Button();
		this.b_MidiCFG.CanFocus = true;
		this.b_MidiCFG.Name = "b_MidiCFG";
		this.b_MidiCFG.UseUnderline = true;
		this.b_MidiCFG.Label = global::Mono.Unix.Catalog.GetString("Midi Settings");
		this.fixed1.Add(this.b_MidiCFG);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.b_MidiCFG]));
		w18.X = 966;
		w18.Y = 674;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.b_setMainOut = new global::Gtk.Button();
		this.b_setMainOut.CanFocus = true;
		this.b_setMainOut.Name = "b_setMainOut";
		this.b_setMainOut.UseUnderline = true;
		this.b_setMainOut.Label = global::Mono.Unix.Catalog.GetString("Set PulseMain Out Volume");
		this.fixed1.Add(this.b_setMainOut);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.b_setMainOut]));
		w19.X = 378;
		w19.Y = 650;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l_hBoxStatus = new global::Gtk.HBox();
		this.l_hBoxStatus.WidthRequest = 1200;
		this.l_hBoxStatus.HeightRequest = 18;
		this.l_hBoxStatus.Name = "l_hBoxStatus";
		this.l_hBoxStatus.Spacing = 6;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stMidiDevice = new global::Gtk.Label();
		this.l_stMidiDevice.Name = "l_stMidiDevice";
		this.l_stMidiDevice.LabelProp = global::Mono.Unix.Catalog.GetString("Device");
		this.l_hBoxStatus.Add(this.l_stMidiDevice);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stMidiDevice]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stMidiMap = new global::Gtk.Label();
		this.l_stMidiMap.Name = "l_stMidiMap";
		this.l_stMidiMap.LabelProp = global::Mono.Unix.Catalog.GetString("Map");
		this.l_hBoxStatus.Add(this.l_stMidiMap);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stMidiMap]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stMidiStatus = new global::Gtk.Label();
		this.l_stMidiStatus.Name = "l_stMidiStatus";
		this.l_stMidiStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Midi");
		this.l_hBoxStatus.Add(this.l_stMidiStatus);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stMidiStatus]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stIdkSomemore = new global::Gtk.Label();
		this.l_stIdkSomemore.Name = "l_stIdkSomemore";
		this.l_stIdkSomemore.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
		this.l_hBoxStatus.Add(this.l_stIdkSomemore);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stIdkSomemore]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stIdkSomemoremore = new global::Gtk.Label();
		this.l_stIdkSomemoremore.Name = "l_stIdkSomemoremore";
		this.l_stIdkSomemoremore.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
		this.l_hBoxStatus.Add(this.l_stIdkSomemoremore);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stIdkSomemoremore]));
		w24.Position = 4;
		w24.Expand = false;
		w24.Fill = false;
		// Container child l_hBoxStatus.Gtk.Box+BoxChild
		this.l_stCopyright = new global::Gtk.Label();
		this.l_stCopyright.Name = "l_stCopyright";
		this.l_stCopyright.LabelProp = global::Mono.Unix.Catalog.GetString("(c) JenniferPrime 2023");
		this.l_stCopyright.Justify = ((global::Gtk.Justification)(1));
		this.l_hBoxStatus.Add(this.l_stCopyright);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.l_hBoxStatus[this.l_stCopyright]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 5;
		w25.Expand = false;
		w25.Fill = false;
		w25.Padding = ((uint)(10));
		this.fixed1.Add(this.l_hBoxStatus);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l_hBoxStatus]));
		w26.Y = 788;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1751;
		this.DefaultHeight = 806;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btn_updateUI.Clicked += new global::System.EventHandler(this.OnBtnUpdateUIClicked);
		this.btn_transportPrev.Clicked += new global::System.EventHandler(this.OnBtnTransportClicked);
		this.btn_transportNext.Clicked += new global::System.EventHandler(this.OnBtnTransportClicked);
		this.btn_transportPlay.Clicked += new global::System.EventHandler(this.OnBtnTransportClicked);
		this.btn_transportPause.Clicked += new global::System.EventHandler(this.OnBtnTransportClicked);
		this.btn_g1_mute.Clicked += new global::System.EventHandler(this.OnBtnG1MuteClicked);
		this.btn_forceCloseMidi.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		this.b_MidiLoad.Clicked += new global::System.EventHandler(this.OnBMidiLoadClicked);
		this.b_MidiCFG.Clicked += new global::System.EventHandler(this.OnBMidiCFGClicked);
		this.b_setMainOut.Clicked += new global::System.EventHandler(this.OnBSetMainOutClicked);
	}
}
