
// This file has been generated by the GUI designer. Do not modify.
namespace SharpMixLinux
{
	public partial class MidiDeviceDialog
	{
		private global::Gtk.Table l_tableContent;

		private global::Gtk.ComboBox cb_MidiDevice;

		private global::Gtk.ComboBox cb_MidiMap;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.Label l_MidiDevice;

		private global::Gtk.Label l_MidiMap;

		private global::Gtk.Label label3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SharpMixLinux.MidiDeviceDialog
			this.Name = "SharpMixLinux.MidiDeviceDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child SharpMixLinux.MidiDeviceDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.l_tableContent = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.l_tableContent.Name = "l_tableContent";
			this.l_tableContent.RowSpacing = ((uint)(6));
			this.l_tableContent.ColumnSpacing = ((uint)(6));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.cb_MidiDevice = global::Gtk.ComboBox.NewText();
			this.cb_MidiDevice.AppendText(global::Mono.Unix.Catalog.GetString("None"));
			this.cb_MidiDevice.Name = "cb_MidiDevice";
			this.l_tableContent.Add(this.cb_MidiDevice);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.cb_MidiDevice]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.cb_MidiMap = global::Gtk.ComboBox.NewText();
			this.cb_MidiMap.AppendText(global::Mono.Unix.Catalog.GetString("None"));
			this.cb_MidiMap.Name = "cb_MidiMap";
			this.l_tableContent.Add(this.cb_MidiMap);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.cb_MidiMap]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.Name = "combobox3";
			this.l_tableContent.Add(this.combobox3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.combobox3]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.l_MidiDevice = new global::Gtk.Label();
			this.l_MidiDevice.Name = "l_MidiDevice";
			this.l_MidiDevice.LabelProp = global::Mono.Unix.Catalog.GetString("Midi Device: ");
			this.l_tableContent.Add(this.l_MidiDevice);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.l_MidiDevice]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.l_MidiMap = new global::Gtk.Label();
			this.l_MidiMap.Name = "l_MidiMap";
			this.l_MidiMap.LabelProp = global::Mono.Unix.Catalog.GetString("Midi Map:");
			this.l_tableContent.Add(this.l_MidiMap);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.l_MidiMap]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child l_tableContent.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.l_tableContent.Add(this.label3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.l_tableContent[this.label3]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.l_tableContent);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.l_tableContent]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child SharpMixLinux.MidiDeviceDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
