
// This file has been generated by the GUI designer. Do not modify.
namespace SharpMixLinux
{
	public partial class AttachAction
	{
		private global::Gtk.Table table2;

		private global::Gtk.ComboBox c_appSink;

		private global::Gtk.ComboBox c_devSink;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.RadioButton r_appSink;

		private global::Gtk.RadioButton r_devSink;

		private global::Gtk.RadioButton radiobutton3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SharpMixLinux.AttachAction
			this.Name = "SharpMixLinux.AttachAction";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child SharpMixLinux.AttachAction.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.c_appSink = global::Gtk.ComboBox.NewText();
			this.c_appSink.AppendText(global::Mono.Unix.Catalog.GetString("None"));
			this.c_appSink.Name = "c_appSink";
			this.c_appSink.Active = 0;
			this.table2.Add(this.c_appSink);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.c_appSink]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.c_devSink = global::Gtk.ComboBox.NewText();
			this.c_devSink.AppendText(global::Mono.Unix.Catalog.GetString("None"));
			this.c_devSink.Name = "c_devSink";
			this.c_devSink.Active = 0;
			this.table2.Add(this.c_devSink);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.c_devSink]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.Name = "comboboxentry1";
			this.table2.Add(this.comboboxentry1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.comboboxentry1]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.r_appSink = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Application"));
			this.r_appSink.CanFocus = true;
			this.r_appSink.Name = "r_appSink";
			this.r_appSink.DrawIndicator = true;
			this.r_appSink.UseUnderline = true;
			this.r_appSink.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.table2.Add(this.r_appSink);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.r_appSink]));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.r_devSink = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Device"));
			this.r_devSink.CanFocus = true;
			this.r_devSink.Name = "r_devSink";
			this.r_devSink.DrawIndicator = true;
			this.r_devSink.UseUnderline = true;
			this.r_devSink.Group = this.r_appSink.Group;
			this.table2.Add(this.r_devSink);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.r_devSink]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Custom"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = this.r_appSink.Group;
			this.table2.Add(this.radiobutton3);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.radiobutton3]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.table2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child SharpMixLinux.AttachAction.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
